package com.huateng.blue.work;

import com.huateng.blue.work.DailyAchieve;
import com.huateng.blue.work.DailyAchieveExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DailyAchieveDAOImpl extends SqlMapClientDaoSupport implements DailyAchieveDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public DailyAchieveDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int countByExample(DailyAchieveExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("daily_achieve.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int deleteByExample(DailyAchieveExample example) {
        int rows = getSqlMapClientTemplate().delete("daily_achieve.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        DailyAchieve key = new DailyAchieve();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("daily_achieve.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void insert(DailyAchieve record) {
        getSqlMapClientTemplate().insert("daily_achieve.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void insertSelective(DailyAchieve record) {
        getSqlMapClientTemplate().insert("daily_achieve.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public List selectByExample(DailyAchieveExample example) {
        List list = getSqlMapClientTemplate().queryForList("daily_achieve.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public DailyAchieve selectByPrimaryKey(Integer id) {
        DailyAchieve key = new DailyAchieve();
        key.setId(id);
        DailyAchieve record = (DailyAchieve) getSqlMapClientTemplate().queryForObject("daily_achieve.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByExampleSelective(DailyAchieve record, DailyAchieveExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("daily_achieve.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByExample(DailyAchieve record, DailyAchieveExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("daily_achieve.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByPrimaryKeySelective(DailyAchieve record) {
        int rows = getSqlMapClientTemplate().update("daily_achieve.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByPrimaryKey(DailyAchieve record) {
        int rows = getSqlMapClientTemplate().update("daily_achieve.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private static class UpdateByExampleParms extends DailyAchieveExample {
        private Object record;

        public UpdateByExampleParms(Object record, DailyAchieveExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}