package com.huateng.blue.work;

public class DailyAchieve {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private Integer distributeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String workId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String workDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.ACHIEVEMENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String achievement;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.ACHIEVE_PERCENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String achievePercent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_achieve.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String inputDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.ID
     *
     * @return the value of daily_achieve.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.ID
     *
     * @param id the value for daily_achieve.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.DISTRIBUTE_ID
     *
     * @return the value of daily_achieve.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public Integer getDistributeId() {
        return distributeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.DISTRIBUTE_ID
     *
     * @param distributeId the value for daily_achieve.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setDistributeId(Integer distributeId) {
        this.distributeId = distributeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.WORK_ID
     *
     * @return the value of daily_achieve.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.WORK_ID
     *
     * @param workId the value for daily_achieve.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.WORK_DATE
     *
     * @return the value of daily_achieve.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.WORK_DATE
     *
     * @param workDate the value for daily_achieve.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate == null ? null : workDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.USER_ID
     *
     * @return the value of daily_achieve.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.USER_ID
     *
     * @param userId the value for daily_achieve.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.ACHIEVEMENT
     *
     * @return the value of daily_achieve.ACHIEVEMENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getAchievement() {
        return achievement;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.ACHIEVEMENT
     *
     * @param achievement the value for daily_achieve.ACHIEVEMENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setAchievement(String achievement) {
        this.achievement = achievement == null ? null : achievement.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.ACHIEVE_PERCENT
     *
     * @return the value of daily_achieve.ACHIEVE_PERCENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getAchievePercent() {
        return achievePercent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.ACHIEVE_PERCENT
     *
     * @param achievePercent the value for daily_achieve.ACHIEVE_PERCENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setAchievePercent(String achievePercent) {
        this.achievePercent = achievePercent == null ? null : achievePercent.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_achieve.INPUT_DATE
     *
     * @return the value of daily_achieve.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_achieve.INPUT_DATE
     *
     * @param inputDate the value for daily_achieve.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }
}