package com.huateng.blue.work;

import com.huateng.blue.work.MainProblem;
import com.huateng.blue.work.MainProblemExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MainProblemDAOImpl extends SqlMapClientDaoSupport implements MainProblemDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public MainProblemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int countByExample(MainProblemExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("main_problem.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int deleteByExample(MainProblemExample example) {
        int rows = getSqlMapClientTemplate().delete("main_problem.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        MainProblem key = new MainProblem();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("main_problem.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public void insert(MainProblem record) {
        getSqlMapClientTemplate().insert("main_problem.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public void insertSelective(MainProblem record) {
        getSqlMapClientTemplate().insert("main_problem.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public List selectByExample(MainProblemExample example) {
        List list = getSqlMapClientTemplate().queryForList("main_problem.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public MainProblem selectByPrimaryKey(Integer id) {
        MainProblem key = new MainProblem();
        key.setId(id);
        MainProblem record = (MainProblem) getSqlMapClientTemplate().queryForObject("main_problem.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int updateByExampleSelective(MainProblem record, MainProblemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("main_problem.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int updateByExample(MainProblem record, MainProblemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("main_problem.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int updateByPrimaryKeySelective(MainProblem record) {
        int rows = getSqlMapClientTemplate().update("main_problem.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public int updateByPrimaryKey(MainProblem record) {
        int rows = getSqlMapClientTemplate().update("main_problem.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    private static class UpdateByExampleParms extends MainProblemExample {
        private Object record;

        public UpdateByExampleParms(Object record, MainProblemExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}