package com.huateng.blue.work;

public class MainProblem {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column main_problem.ID
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column main_problem.CONTENT
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    private String content;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column main_problem.ID
     *
     * @return the value of main_problem.ID
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column main_problem.ID
     *
     * @param id the value for main_problem.ID
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column main_problem.CONTENT
     *
     * @return the value of main_problem.CONTENT
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column main_problem.CONTENT
     *
     * @param content the value for main_problem.CONTENT
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}