package com.huateng.blue.work;

public class SignRecordKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sign_record.RECORD_DATE
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private String recordDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sign_record.RECORD_TYPE
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private String recordType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sign_record.USER_ID
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private String userId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sign_record.RECORD_DATE
     *
     * @return the value of sign_record.RECORD_DATE
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sign_record.RECORD_DATE
     *
     * @param recordDate the value for sign_record.RECORD_DATE
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate == null ? null : recordDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sign_record.RECORD_TYPE
     *
     * @return the value of sign_record.RECORD_TYPE
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sign_record.RECORD_TYPE
     *
     * @param recordType the value for sign_record.RECORD_TYPE
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType == null ? null : recordType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sign_record.USER_ID
     *
     * @return the value of sign_record.USER_ID
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sign_record.USER_ID
     *
     * @param userId the value for sign_record.USER_ID
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}