package com.huateng.blue.work;

import com.huateng.blue.work.SignRecord;
import com.huateng.blue.work.SignRecordExample;
import com.huateng.blue.work.SignRecordKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SignRecordDAOImpl extends SqlMapClientDaoSupport implements SignRecordDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public SignRecordDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int countByExample(SignRecordExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sign_record.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int deleteByExample(SignRecordExample example) {
        int rows = getSqlMapClientTemplate().delete("sign_record.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int deleteByPrimaryKey(SignRecordKey key) {
        int rows = getSqlMapClientTemplate().delete("sign_record.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void insert(SignRecord record) {
        getSqlMapClientTemplate().insert("sign_record.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void insertSelective(SignRecord record) {
        getSqlMapClientTemplate().insert("sign_record.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public List selectByExample(SignRecordExample example) {
        List list = getSqlMapClientTemplate().queryForList("sign_record.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public SignRecord selectByPrimaryKey(SignRecordKey key) {
        SignRecord record = (SignRecord) getSqlMapClientTemplate().queryForObject("sign_record.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int updateByExampleSelective(SignRecord record, SignRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sign_record.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int updateByExample(SignRecord record, SignRecordExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sign_record.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int updateByPrimaryKeySelective(SignRecord record) {
        int rows = getSqlMapClientTemplate().update("sign_record.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public int updateByPrimaryKey(SignRecord record) {
        int rows = getSqlMapClientTemplate().update("sign_record.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sign_record
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private static class UpdateByExampleParms extends SignRecordExample {
        private Object record;

        public UpdateByExampleParms(Object record, SignRecordExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}