package com.huateng.blue.work;

public class WorkDaily {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private Integer distributeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String workId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String workDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.CONTENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_daily.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String inputDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.ID
     *
     * @return the value of work_daily.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.ID
     *
     * @param id the value for work_daily.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.DISTRIBUTE_ID
     *
     * @return the value of work_daily.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public Integer getDistributeId() {
        return distributeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.DISTRIBUTE_ID
     *
     * @param distributeId the value for work_daily.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setDistributeId(Integer distributeId) {
        this.distributeId = distributeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.WORK_ID
     *
     * @return the value of work_daily.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.WORK_ID
     *
     * @param workId the value for work_daily.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.WORK_DATE
     *
     * @return the value of work_daily.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.WORK_DATE
     *
     * @param workDate the value for work_daily.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate == null ? null : workDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.USER_ID
     *
     * @return the value of work_daily.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.USER_ID
     *
     * @param userId the value for work_daily.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.CONTENT
     *
     * @return the value of work_daily.CONTENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.CONTENT
     *
     * @param content the value for work_daily.CONTENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_daily.INPUT_DATE
     *
     * @return the value of work_daily.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_daily.INPUT_DATE
     *
     * @param inputDate the value for work_daily.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }
}