package com.huateng.blue.work;

import com.eis.base.BaseForm;

public class WorkDistributeForm extends BaseForm {
	private String reason;
	
	 /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.WORK_ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String workId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.USER_ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.START_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.END_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.CONTENT
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.WORK_STATUS
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String workStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.INPUT_USER
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String inputUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.INPUT_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private String inputDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_distribute.NOTIFY_DAY
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private Integer notifyDay;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.ID
     *
     * @return the value of work_distribute.ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.ID
     *
     * @param id the value for work_distribute.ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.WORK_ID
     *
     * @return the value of work_distribute.WORK_ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.WORK_ID
     *
     * @param workId the value for work_distribute.WORK_ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.USER_ID
     *
     * @return the value of work_distribute.USER_ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.USER_ID
     *
     * @param userId the value for work_distribute.USER_ID
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.START_DATE
     *
     * @return the value of work_distribute.START_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.START_DATE
     *
     * @param startDate the value for work_distribute.START_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.END_DATE
     *
     * @return the value of work_distribute.END_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.END_DATE
     *
     * @param endDate the value for work_distribute.END_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.CONTENT
     *
     * @return the value of work_distribute.CONTENT
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.CONTENT
     *
     * @param content the value for work_distribute.CONTENT
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.WORK_STATUS
     *
     * @return the value of work_distribute.WORK_STATUS
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.WORK_STATUS
     *
     * @param workStatus the value for work_distribute.WORK_STATUS
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus == null ? null : workStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.INPUT_USER
     *
     * @return the value of work_distribute.INPUT_USER
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.INPUT_USER
     *
     * @param inputUser the value for work_distribute.INPUT_USER
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.INPUT_DATE
     *
     * @return the value of work_distribute.INPUT_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.INPUT_DATE
     *
     * @param inputDate the value for work_distribute.INPUT_DATE
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_distribute.NOTIFY_DAY
     *
     * @return the value of work_distribute.NOTIFY_DAY
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public Integer getNotifyDay() {
        return notifyDay;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_distribute.NOTIFY_DAY
     *
     * @param notifyDay the value for work_distribute.NOTIFY_DAY
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setNotifyDay(Integer notifyDay) {
        this.notifyDay = notifyDay;
    }

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
}
