package com.huateng.blue.work;

import com.huateng.blue.work.WorkDistribute;
import com.huateng.blue.work.WorkDistributeExample;
import java.util.List;

public interface WorkDistributeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int countByExample(WorkDistributeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int deleteByExample(WorkDistributeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    void insert(WorkDistribute record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    void insertSelective(WorkDistribute record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    List selectByExample(WorkDistributeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    WorkDistribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int updateByExampleSelective(WorkDistribute record, WorkDistributeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int updateByExample(WorkDistribute record, WorkDistributeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int updateByPrimaryKeySelective(WorkDistribute record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    int updateByPrimaryKey(WorkDistribute record);
}