package com.huateng.blue.work;

import com.huateng.blue.work.WorkDistribute;
import com.huateng.blue.work.WorkDistributeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WorkDistributeDAOImpl extends SqlMapClientDaoSupport implements WorkDistributeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public WorkDistributeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int countByExample(WorkDistributeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("work_distribute.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int deleteByExample(WorkDistributeExample example) {
        int rows = getSqlMapClientTemplate().delete("work_distribute.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        WorkDistribute key = new WorkDistribute();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("work_distribute.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void insert(WorkDistribute record) {
        getSqlMapClientTemplate().insert("work_distribute.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void insertSelective(WorkDistribute record) {
        getSqlMapClientTemplate().insert("work_distribute.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public List selectByExample(WorkDistributeExample example) {
        List list = getSqlMapClientTemplate().queryForList("work_distribute.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public WorkDistribute selectByPrimaryKey(Integer id) {
        WorkDistribute key = new WorkDistribute();
        key.setId(id);
        WorkDistribute record = (WorkDistribute) getSqlMapClientTemplate().queryForObject("work_distribute.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int updateByExampleSelective(WorkDistribute record, WorkDistributeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("work_distribute.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int updateByExample(WorkDistribute record, WorkDistributeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("work_distribute.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int updateByPrimaryKeySelective(WorkDistribute record) {
        int rows = getSqlMapClientTemplate().update("work_distribute.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public int updateByPrimaryKey(WorkDistribute record) {
        int rows = getSqlMapClientTemplate().update("work_distribute.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    private static class UpdateByExampleParms extends WorkDistributeExample {
        private Object record;

        public UpdateByExampleParms(Object record, WorkDistributeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}