package com.huateng.blue.work;

import com.huateng.blue.work.DailyAchieve;
import com.huateng.blue.work.DailyAchieveExample;
import java.util.List;

public interface DailyAchieveDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int countByExample(DailyAchieveExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int deleteByExample(DailyAchieveExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    void insert(DailyAchieve record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    void insertSelective(DailyAchieve record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    List selectByExample(DailyAchieveExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    DailyAchieve selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByExampleSelective(DailyAchieve record, DailyAchieveExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByExample(DailyAchieve record, DailyAchieveExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByPrimaryKeySelective(DailyAchieve record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table daily_achieve
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByPrimaryKey(DailyAchieve record);
}