package com.huateng.blue.work;

public class DailyIssue {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private Integer distributeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String workId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String workDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.ISSUE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String issue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.ISSUE_PERCENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String issuePercent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column daily_issue.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private String inputDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.ID
     *
     * @return the value of daily_issue.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.ID
     *
     * @param id the value for daily_issue.ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.DISTRIBUTE_ID
     *
     * @return the value of daily_issue.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public Integer getDistributeId() {
        return distributeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.DISTRIBUTE_ID
     *
     * @param distributeId the value for daily_issue.DISTRIBUTE_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setDistributeId(Integer distributeId) {
        this.distributeId = distributeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.WORK_ID
     *
     * @return the value of daily_issue.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.WORK_ID
     *
     * @param workId the value for daily_issue.WORK_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.WORK_DATE
     *
     * @return the value of daily_issue.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.WORK_DATE
     *
     * @param workDate the value for daily_issue.WORK_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate == null ? null : workDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.USER_ID
     *
     * @return the value of daily_issue.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.USER_ID
     *
     * @param userId the value for daily_issue.USER_ID
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.ISSUE
     *
     * @return the value of daily_issue.ISSUE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getIssue() {
        return issue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.ISSUE
     *
     * @param issue the value for daily_issue.ISSUE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setIssue(String issue) {
        this.issue = issue == null ? null : issue.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.ISSUE_PERCENT
     *
     * @return the value of daily_issue.ISSUE_PERCENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getIssuePercent() {
        return issuePercent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.ISSUE_PERCENT
     *
     * @param issuePercent the value for daily_issue.ISSUE_PERCENT
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setIssuePercent(String issuePercent) {
        this.issuePercent = issuePercent == null ? null : issuePercent.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column daily_issue.INPUT_DATE
     *
     * @return the value of daily_issue.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column daily_issue.INPUT_DATE
     *
     * @param inputDate the value for daily_issue.INPUT_DATE
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }
}