package com.huateng.blue.work;

import com.huateng.blue.work.MainProblem;
import com.huateng.blue.work.MainProblemExample;
import java.util.List;

public interface MainProblemDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int countByExample(MainProblemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int deleteByExample(MainProblemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    void insert(MainProblem record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    void insertSelective(MainProblem record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    List selectByExample(MainProblemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    MainProblem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int updateByExampleSelective(MainProblem record, MainProblemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int updateByExample(MainProblem record, MainProblemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int updateByPrimaryKeySelective(MainProblem record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table main_problem
     *
     * @ibatorgenerated Fri Sep 02 09:14:40 CST 2011
     */
    int updateByPrimaryKey(MainProblem record);
}