package com.huateng.blue.work;

public class SignRecord extends SignRecordKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sign_record.RECORD_TIME
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private String recordTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sign_record.IS_MODIFIED
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private String isModified;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sign_record.MODIFY_USER
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    private String modifyUser;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sign_record.RECORD_TIME
     *
     * @return the value of sign_record.RECORD_TIME
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public String getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sign_record.RECORD_TIME
     *
     * @param recordTime the value for sign_record.RECORD_TIME
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void setRecordTime(String recordTime) {
        this.recordTime = recordTime == null ? null : recordTime.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sign_record.IS_MODIFIED
     *
     * @return the value of sign_record.IS_MODIFIED
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public String getIsModified() {
        return isModified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sign_record.IS_MODIFIED
     *
     * @param isModified the value for sign_record.IS_MODIFIED
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void setIsModified(String isModified) {
        this.isModified = isModified == null ? null : isModified.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sign_record.MODIFY_USER
     *
     * @return the value of sign_record.MODIFY_USER
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sign_record.MODIFY_USER
     *
     * @param modifyUser the value for sign_record.MODIFY_USER
     *
     * @ibatorgenerated Tue Nov 01 09:58:54 CST 2011
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}