package com.huateng.blue.work;

import com.huateng.blue.work.WorkList;
import com.huateng.blue.work.WorkListExample;
import java.util.List;

public interface WorkListDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int countByExample(WorkListExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int deleteByExample(WorkListExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int deleteByPrimaryKey(String workId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    void insert(WorkList record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    void insertSelective(WorkList record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    List selectByExample(WorkListExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    WorkList selectByPrimaryKey(String workId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int updateByExampleSelective(WorkList record, WorkListExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int updateByExample(WorkList record, WorkListExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int updateByPrimaryKeySelective(WorkList record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    int updateByPrimaryKey(WorkList record);
}