package com.huateng.blue.work;

import com.huateng.blue.work.WorkDaily;
import com.huateng.blue.work.WorkDailyExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WorkDailyDAOImpl extends SqlMapClientDaoSupport implements WorkDailyDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public WorkDailyDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int countByExample(WorkDailyExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("work_daily.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int deleteByExample(WorkDailyExample example) {
        int rows = getSqlMapClientTemplate().delete("work_daily.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        WorkDaily key = new WorkDaily();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("work_daily.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void insert(WorkDaily record) {
        getSqlMapClientTemplate().insert("work_daily.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public void insertSelective(WorkDaily record) {
        getSqlMapClientTemplate().insert("work_daily.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public List selectByExample(WorkDailyExample example) {
        List list = getSqlMapClientTemplate().queryForList("work_daily.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public WorkDaily selectByPrimaryKey(Integer id) {
        WorkDaily key = new WorkDaily();
        key.setId(id);
        WorkDaily record = (WorkDaily) getSqlMapClientTemplate().queryForObject("work_daily.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByExampleSelective(WorkDaily record, WorkDailyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("work_daily.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByExample(WorkDaily record, WorkDailyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("work_daily.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByPrimaryKeySelective(WorkDaily record) {
        int rows = getSqlMapClientTemplate().update("work_daily.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    public int updateByPrimaryKey(WorkDaily record) {
        int rows = getSqlMapClientTemplate().update("work_daily.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    private static class UpdateByExampleParms extends WorkDailyExample {
        private Object record;

        public UpdateByExampleParms(Object record, WorkDailyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}