package com.huateng.blue.work;

import com.huateng.blue.work.WorkDaily;
import com.huateng.blue.work.WorkDailyExample;
import java.util.List;

public interface WorkDailyDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int countByExample(WorkDailyExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int deleteByExample(WorkDailyExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    void insert(WorkDaily record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    void insertSelective(WorkDaily record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    List selectByExample(WorkDailyExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    WorkDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByExampleSelective(WorkDaily record, WorkDailyExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByExample(WorkDaily record, WorkDailyExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByPrimaryKeySelective(WorkDaily record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_daily
     *
     * @ibatorgenerated Wed Aug 10 17:28:40 CST 2011
     */
    int updateByPrimaryKey(WorkDaily record);
}