package com.huateng.blue.work;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WorkDistributeExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public WorkDistributeExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    protected WorkDistributeExample(WorkDistributeExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table work_distribute
     *
     * @ibatorgenerated Mon Jul 25 15:07:09 CST 2011
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andWorkIdIsNull() {
            addCriterion("WORK_ID is null");
            return this;
        }

        public Criteria andWorkIdIsNotNull() {
            addCriterion("WORK_ID is not null");
            return this;
        }

        public Criteria andWorkIdEqualTo(String value) {
            addCriterion("WORK_ID =", value, "workId");
            return this;
        }

        public Criteria andWorkIdNotEqualTo(String value) {
            addCriterion("WORK_ID <>", value, "workId");
            return this;
        }

        public Criteria andWorkIdGreaterThan(String value) {
            addCriterion("WORK_ID >", value, "workId");
            return this;
        }

        public Criteria andWorkIdGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_ID >=", value, "workId");
            return this;
        }

        public Criteria andWorkIdLessThan(String value) {
            addCriterion("WORK_ID <", value, "workId");
            return this;
        }

        public Criteria andWorkIdLessThanOrEqualTo(String value) {
            addCriterion("WORK_ID <=", value, "workId");
            return this;
        }

        public Criteria andWorkIdLike(String value) {
            addCriterion("WORK_ID like", value, "workId");
            return this;
        }

        public Criteria andWorkIdNotLike(String value) {
            addCriterion("WORK_ID not like", value, "workId");
            return this;
        }

        public Criteria andWorkIdIn(List values) {
            addCriterion("WORK_ID in", values, "workId");
            return this;
        }

        public Criteria andWorkIdNotIn(List values) {
            addCriterion("WORK_ID not in", values, "workId");
            return this;
        }

        public Criteria andWorkIdBetween(String value1, String value2) {
            addCriterion("WORK_ID between", value1, value2, "workId");
            return this;
        }

        public Criteria andWorkIdNotBetween(String value1, String value2) {
            addCriterion("WORK_ID not between", value1, value2, "workId");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return this;
        }

        public Criteria andStartDateEqualTo(String value) {
            addCriterion("START_DATE =", value, "startDate");
            return this;
        }

        public Criteria andStartDateNotEqualTo(String value) {
            addCriterion("START_DATE <>", value, "startDate");
            return this;
        }

        public Criteria andStartDateGreaterThan(String value) {
            addCriterion("START_DATE >", value, "startDate");
            return this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("START_DATE >=", value, "startDate");
            return this;
        }

        public Criteria andStartDateLessThan(String value) {
            addCriterion("START_DATE <", value, "startDate");
            return this;
        }

        public Criteria andStartDateLessThanOrEqualTo(String value) {
            addCriterion("START_DATE <=", value, "startDate");
            return this;
        }

        public Criteria andStartDateLike(String value) {
            addCriterion("START_DATE like", value, "startDate");
            return this;
        }

        public Criteria andStartDateNotLike(String value) {
            addCriterion("START_DATE not like", value, "startDate");
            return this;
        }

        public Criteria andStartDateIn(List values) {
            addCriterion("START_DATE in", values, "startDate");
            return this;
        }

        public Criteria andStartDateNotIn(List values) {
            addCriterion("START_DATE not in", values, "startDate");
            return this;
        }

        public Criteria andStartDateBetween(String value1, String value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return this;
        }

        public Criteria andStartDateNotBetween(String value1, String value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("END_DATE =", value, "endDate");
            return this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("END_DATE <>", value, "endDate");
            return this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("END_DATE >", value, "endDate");
            return this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("END_DATE >=", value, "endDate");
            return this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("END_DATE <", value, "endDate");
            return this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("END_DATE <=", value, "endDate");
            return this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("END_DATE like", value, "endDate");
            return this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("END_DATE not like", value, "endDate");
            return this;
        }

        public Criteria andEndDateIn(List values) {
            addCriterion("END_DATE in", values, "endDate");
            return this;
        }

        public Criteria andEndDateNotIn(List values) {
            addCriterion("END_DATE not in", values, "endDate");
            return this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return this;
        }

        public Criteria andContentIn(List values) {
            addCriterion("CONTENT in", values, "content");
            return this;
        }

        public Criteria andContentNotIn(List values) {
            addCriterion("CONTENT not in", values, "content");
            return this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return this;
        }

        public Criteria andWorkStatusIsNull() {
            addCriterion("WORK_STATUS is null");
            return this;
        }

        public Criteria andWorkStatusIsNotNull() {
            addCriterion("WORK_STATUS is not null");
            return this;
        }

        public Criteria andWorkStatusEqualTo(String value) {
            addCriterion("WORK_STATUS =", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusNotEqualTo(String value) {
            addCriterion("WORK_STATUS <>", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusGreaterThan(String value) {
            addCriterion("WORK_STATUS >", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_STATUS >=", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusLessThan(String value) {
            addCriterion("WORK_STATUS <", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusLessThanOrEqualTo(String value) {
            addCriterion("WORK_STATUS <=", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusLike(String value) {
            addCriterion("WORK_STATUS like", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusNotLike(String value) {
            addCriterion("WORK_STATUS not like", value, "workStatus");
            return this;
        }

        public Criteria andWorkStatusIn(List values) {
            addCriterion("WORK_STATUS in", values, "workStatus");
            return this;
        }

        public Criteria andWorkStatusNotIn(List values) {
            addCriterion("WORK_STATUS not in", values, "workStatus");
            return this;
        }

        public Criteria andWorkStatusBetween(String value1, String value2) {
            addCriterion("WORK_STATUS between", value1, value2, "workStatus");
            return this;
        }

        public Criteria andWorkStatusNotBetween(String value1, String value2) {
            addCriterion("WORK_STATUS not between", value1, value2, "workStatus");
            return this;
        }

        public Criteria andInputUserIsNull() {
            addCriterion("INPUT_USER is null");
            return this;
        }

        public Criteria andInputUserIsNotNull() {
            addCriterion("INPUT_USER is not null");
            return this;
        }

        public Criteria andInputUserEqualTo(String value) {
            addCriterion("INPUT_USER =", value, "inputUser");
            return this;
        }

        public Criteria andInputUserNotEqualTo(String value) {
            addCriterion("INPUT_USER <>", value, "inputUser");
            return this;
        }

        public Criteria andInputUserGreaterThan(String value) {
            addCriterion("INPUT_USER >", value, "inputUser");
            return this;
        }

        public Criteria andInputUserGreaterThanOrEqualTo(String value) {
            addCriterion("INPUT_USER >=", value, "inputUser");
            return this;
        }

        public Criteria andInputUserLessThan(String value) {
            addCriterion("INPUT_USER <", value, "inputUser");
            return this;
        }

        public Criteria andInputUserLessThanOrEqualTo(String value) {
            addCriterion("INPUT_USER <=", value, "inputUser");
            return this;
        }

        public Criteria andInputUserLike(String value) {
            addCriterion("INPUT_USER like", value, "inputUser");
            return this;
        }

        public Criteria andInputUserNotLike(String value) {
            addCriterion("INPUT_USER not like", value, "inputUser");
            return this;
        }

        public Criteria andInputUserIn(List values) {
            addCriterion("INPUT_USER in", values, "inputUser");
            return this;
        }

        public Criteria andInputUserNotIn(List values) {
            addCriterion("INPUT_USER not in", values, "inputUser");
            return this;
        }

        public Criteria andInputUserBetween(String value1, String value2) {
            addCriterion("INPUT_USER between", value1, value2, "inputUser");
            return this;
        }

        public Criteria andInputUserNotBetween(String value1, String value2) {
            addCriterion("INPUT_USER not between", value1, value2, "inputUser");
            return this;
        }

        public Criteria andInputDateIsNull() {
            addCriterion("INPUT_DATE is null");
            return this;
        }

        public Criteria andInputDateIsNotNull() {
            addCriterion("INPUT_DATE is not null");
            return this;
        }

        public Criteria andInputDateEqualTo(String value) {
            addCriterion("INPUT_DATE =", value, "inputDate");
            return this;
        }

        public Criteria andInputDateNotEqualTo(String value) {
            addCriterion("INPUT_DATE <>", value, "inputDate");
            return this;
        }

        public Criteria andInputDateGreaterThan(String value) {
            addCriterion("INPUT_DATE >", value, "inputDate");
            return this;
        }

        public Criteria andInputDateGreaterThanOrEqualTo(String value) {
            addCriterion("INPUT_DATE >=", value, "inputDate");
            return this;
        }

        public Criteria andInputDateLessThan(String value) {
            addCriterion("INPUT_DATE <", value, "inputDate");
            return this;
        }

        public Criteria andInputDateLessThanOrEqualTo(String value) {
            addCriterion("INPUT_DATE <=", value, "inputDate");
            return this;
        }

        public Criteria andInputDateLike(String value) {
            addCriterion("INPUT_DATE like", value, "inputDate");
            return this;
        }

        public Criteria andInputDateNotLike(String value) {
            addCriterion("INPUT_DATE not like", value, "inputDate");
            return this;
        }

        public Criteria andInputDateIn(List values) {
            addCriterion("INPUT_DATE in", values, "inputDate");
            return this;
        }

        public Criteria andInputDateNotIn(List values) {
            addCriterion("INPUT_DATE not in", values, "inputDate");
            return this;
        }

        public Criteria andInputDateBetween(String value1, String value2) {
            addCriterion("INPUT_DATE between", value1, value2, "inputDate");
            return this;
        }

        public Criteria andInputDateNotBetween(String value1, String value2) {
            addCriterion("INPUT_DATE not between", value1, value2, "inputDate");
            return this;
        }

        public Criteria andNotifyDayIsNull() {
            addCriterion("NOTIFY_DAY is null");
            return this;
        }

        public Criteria andNotifyDayIsNotNull() {
            addCriterion("NOTIFY_DAY is not null");
            return this;
        }

        public Criteria andNotifyDayEqualTo(Integer value) {
            addCriterion("NOTIFY_DAY =", value, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayNotEqualTo(Integer value) {
            addCriterion("NOTIFY_DAY <>", value, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayGreaterThan(Integer value) {
            addCriterion("NOTIFY_DAY >", value, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("NOTIFY_DAY >=", value, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayLessThan(Integer value) {
            addCriterion("NOTIFY_DAY <", value, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayLessThanOrEqualTo(Integer value) {
            addCriterion("NOTIFY_DAY <=", value, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayIn(List values) {
            addCriterion("NOTIFY_DAY in", values, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayNotIn(List values) {
            addCriterion("NOTIFY_DAY not in", values, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayBetween(Integer value1, Integer value2) {
            addCriterion("NOTIFY_DAY between", value1, value2, "notifyDay");
            return this;
        }

        public Criteria andNotifyDayNotBetween(Integer value1, Integer value2) {
            addCriterion("NOTIFY_DAY not between", value1, value2, "notifyDay");
            return this;
        }
    }
}