package com.huateng.blue.work;

import com.huateng.blue.work.WorkList;
import com.huateng.blue.work.WorkListExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WorkListDAOImpl extends SqlMapClientDaoSupport implements WorkListDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public WorkListDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int countByExample(WorkListExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("work_list.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int deleteByExample(WorkListExample example) {
        int rows = getSqlMapClientTemplate().delete("work_list.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int deleteByPrimaryKey(String workId) {
        WorkList key = new WorkList();
        key.setWorkId(workId);
        int rows = getSqlMapClientTemplate().delete("work_list.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void insert(WorkList record) {
        getSqlMapClientTemplate().insert("work_list.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void insertSelective(WorkList record) {
        getSqlMapClientTemplate().insert("work_list.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public List selectByExample(WorkListExample example) {
        List list = getSqlMapClientTemplate().queryForList("work_list.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public WorkList selectByPrimaryKey(String workId) {
        WorkList key = new WorkList();
        key.setWorkId(workId);
        WorkList record = (WorkList) getSqlMapClientTemplate().queryForObject("work_list.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int updateByExampleSelective(WorkList record, WorkListExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("work_list.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int updateByExample(WorkList record, WorkListExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("work_list.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int updateByPrimaryKeySelective(WorkList record) {
        int rows = getSqlMapClientTemplate().update("work_list.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public int updateByPrimaryKey(WorkList record) {
        int rows = getSqlMapClientTemplate().update("work_list.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table work_list
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private static class UpdateByExampleParms extends WorkListExample {
        private Object record;

        public UpdateByExampleParms(Object record, WorkListExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}