package com.huateng.blue.work;

public class WorkList {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.WORK_ID
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String workId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.WORK_NAME
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String workName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.CONTENT
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String content;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.WORK_STATUS
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String workStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.START_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String startDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.END_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String endDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.INPUT_USER
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String inputUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.INPUT_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String inputDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column work_list.IS_MAIN
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    private String isMain;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.WORK_ID
     *
     * @return the value of work_list.WORK_ID
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.WORK_ID
     *
     * @param workId the value for work_list.WORK_ID
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.WORK_NAME
     *
     * @return the value of work_list.WORK_NAME
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getWorkName() {
        return workName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.WORK_NAME
     *
     * @param workName the value for work_list.WORK_NAME
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setWorkName(String workName) {
        this.workName = workName == null ? null : workName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.CONTENT
     *
     * @return the value of work_list.CONTENT
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.CONTENT
     *
     * @param content the value for work_list.CONTENT
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.WORK_STATUS
     *
     * @return the value of work_list.WORK_STATUS
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.WORK_STATUS
     *
     * @param workStatus the value for work_list.WORK_STATUS
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus == null ? null : workStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.START_DATE
     *
     * @return the value of work_list.START_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.START_DATE
     *
     * @param startDate the value for work_list.START_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.END_DATE
     *
     * @return the value of work_list.END_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.END_DATE
     *
     * @param endDate the value for work_list.END_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.INPUT_USER
     *
     * @return the value of work_list.INPUT_USER
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getInputUser() {
        return inputUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.INPUT_USER
     *
     * @param inputUser the value for work_list.INPUT_USER
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setInputUser(String inputUser) {
        this.inputUser = inputUser == null ? null : inputUser.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.INPUT_DATE
     *
     * @return the value of work_list.INPUT_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.INPUT_DATE
     *
     * @param inputDate the value for work_list.INPUT_DATE
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column work_list.IS_MAIN
     *
     * @return the value of work_list.IS_MAIN
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public String getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column work_list.IS_MAIN
     *
     * @param isMain the value for work_list.IS_MAIN
     *
     * @ibatorgenerated Tue Sep 20 10:30:28 CST 2011
     */
    public void setIsMain(String isMain) {
        this.isMain = isMain == null ? null : isMain.trim();
    }
}